language: php
php:
  - 7.1
  - 7.2
cache:
  directories:
    - vendor
before_install:
  - composer validate
install:
  - composer install -o --prefer-source --no-interaction
script:
  - vendor/bin/phpcs --standard=PSR2 src
  - vendor/bin/phpunit
